# GitHub CI build pipeline
name: BotLine build pipeline

on:
  push:
    branches:
      - master
      - main
  pull_request:
    branches:
      - master
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
        architecture: x64
        cache: 'pip'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        if [ ! -f .env ]; then cp .env.example .env; fi
    - name: Run tests only
      run: |
        pytest
    - name: Run tests and coverage
      run: |
        pip list
        nosetests --config=config.cfg
        genbadge tests -i tests/report/xunit.xml -o tests/report/badge-tests.svg
        genbadge coverage -i tests/report/coverage.xml -o tests/report/badge-coverage.svg
    - name: Archive code coverage html report
      uses: actions/upload-artifact@v2
      with:
        name: tests-report
        path: tests/report
    - name: Run package creation
      run: |
        python setup.py sdist bdist_wheel
    - name: Archive package
      uses: actions/upload-artifact@v2
      with:
        name: botline
        path: dist  

